eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: spring-feign-01
#properties文件
#feign.hystrix.enabled=true
#断路器配置
feign:
  hystrix:
    enabled: true